name: Release
on: 
  push:
    branches:
      - main
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy Website
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.nate.online
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./src/
        server-dir: ./public_html/